/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package1;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ken Española
 */
public class history extends javax.swing.JFrame {

    /**
     * Creates new form history
     */
    public history() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        itemname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jButtonreset = new javax.swing.JButton();
        ComboBoxdesc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxstatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        itemnameprice = new javax.swing.JTextField();
        jButtonsave1 = new javax.swing.JButton();
        jButtonclose1 = new javax.swing.JButton();
        jButtonclose2 = new javax.swing.JButton();
        jButtonclose3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        itemnameid1 = new javax.swing.JTextField();
        jButtonsave2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 46, 74));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("ITEM NAME");

        itemname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("QUANTITY");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("ITEM DESCRIPTION");

        quantity.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        jButtonreset.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButtonreset.setText("RESET");
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });

        ComboBoxdesc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        ComboBoxdesc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Books", "Uniform", "Paper", "Ink" }));
        ComboBoxdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxdescActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "reference id", "itemname", "itemdesc", "quantity", "price", "status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("STATUS");

        ComboBoxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN STOCK", "OUT OF STOCK", " " }));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("REFERENCE ID");

        itemnameprice.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jButtonsave1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButtonsave1.setText("VIEW");
        jButtonsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsave1ActionPerformed(evt);
            }
        });

        jButtonclose1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButtonclose1.setText("CLOSE");
        jButtonclose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclose1ActionPerformed(evt);
            }
        });

        jButtonclose2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButtonclose2.setText("UPDATE");
        jButtonclose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclose2ActionPerformed(evt);
            }
        });

        jButtonclose3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButtonclose3.setText("DELETE");
        jButtonclose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclose3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setText("PRICE");

        itemnameid1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jButtonsave2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButtonsave2.setText("SAVE");
        jButtonsave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsave2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemnameprice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxstatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ComboBoxdesc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 75, Short.MAX_VALUE))
                                    .addComponent(quantity)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonsave2)
                            .addComponent(jButtonsave1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonclose2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonclose3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonreset)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonclose1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(868, 868, 868)
                    .addComponent(itemnameid1)
                    .addGap(50, 50, 50)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(itemnameprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonsave2)
                            .addComponent(jButtonclose2)
                            .addComponent(jButtonclose3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonsave1)
                            .addComponent(jButtonreset)
                            .addComponent(jButtonclose1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(itemnameid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(501, Short.MAX_VALUE)))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PURCHASE HISTORY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1318, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        itemnameid1.setText("");
        itemname.setText("");
        ComboBoxdesc.setSelectedItem("BOOK");
        quantity.setText("");
        ComboBoxstatus.setSelectedItem("IN STOCK");
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void ComboBoxdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxdescActionPerformed

    }//GEN-LAST:event_ComboBoxdescActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

        String tableitemnameid = tblModel.getValueAt(jTable1. getSelectedRow(),1).toString();
        String tableitemname = tblModel.getValueAt(jTable1. getSelectedRow(),2).toString();
        String tableComboBoxdesc = tblModel.getValueAt(jTable1. getSelectedRow(),3).toString();
        String tablequantity = tblModel.getValueAt(jTable1. getSelectedRow(),4).toString();
        String tableprice= tblModel.getValueAt(jTable1. getSelectedRow(),5).toString();
        String tableComboBoxstatus = tblModel.getValueAt(jTable1. getSelectedRow(),6).toString();

        itemnameid1.setText(tableitemnameid);
        itemname.setText(tableitemname);
        ComboBoxdesc.setSelectedItem(tableComboBoxdesc);
        quantity.setText(tablequantity);
        itemnameprice.setText(tableprice);
        ComboBoxstatus.setSelectedItem(tableComboBoxstatus);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsave1ActionPerformed
        String sql = "SELECT * FROM items";
        try {
            ps = con.prepareStatement(sql);
            set = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while(set.next()) {
                model.addRow(new String[]{
                    set.getString(1),
                    set.getString(2),
                    set.getString(3),
                    set.getString(4),
                    set.getString(5),
                    set.getString(6),
                    set.getString(7)

                });
            }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "Error refreshing table: " + ex.getMessage());
        } finally {
            try {
                if(set != null) set.close();
                if(ps != null) ps.close();
            } catch(Exception e) {
                // Handle cleanup errors silently
            }
        }
    }//GEN-LAST:event_jButtonsave1ActionPerformed

    private void jButtonclose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclose1ActionPerformed
        mainframe mf = new mainframe();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonclose1ActionPerformed

    private void jButtonclose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclose2ActionPerformed

        String itemnamer = itemnameid1.getText();
        String itemnames = itemname.getText();
        String values = ComboBoxdesc.getSelectedItem().toString();
        String quants = quantity.getText();
        String valuebr = itemnameprice.getText();
        String valueb = ComboBoxstatus.getSelectedItem().toString();

        String query = "UPDATE items SET itemname=?, itemdesc=?, quantity=?,price=?,status=? WHERE referenceid=?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(1,itemnames);  // Changed from itemnamer to itemnames
            ps.setString(2,values);     // Changed order to match query columns
            ps.setString(3,quants);
            ps.setString(4,valuebr);
            ps.setString(5,valueb);
            ps.setString(6,itemnamer);  // referenceid should be itemnamer

            if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"Item Updated Successfully!");  // Changed message
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Update Failed!");  // Changed message
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: " + ex.getMessage());  // Added error message
        }
    }//GEN-LAST:event_jButtonclose2ActionPerformed

    private void jButtonclose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclose3ActionPerformed
        String itemnamer = itemnameid1.getText();

        String query = "DELETE FROM items WHERE referenceid=?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,itemnamer);

            if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"Item Deleted Successfully!");

            }
            else
            {
                JOptionPane.showMessageDialog(null,"No Item Found to Delete!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonclose3ActionPerformed

    private void jButtonsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsave2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsave2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxdesc;
    private javax.swing.JComboBox<String> ComboBoxstatus;
    private javax.swing.JTextField itemname;
    private javax.swing.JTextField itemnameid1;
    private javax.swing.JTextField itemnameprice;
    private javax.swing.JButton jButtonclose1;
    private javax.swing.JButton jButtonclose2;
    private javax.swing.JButton jButtonclose3;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JButton jButtonsave1;
    private javax.swing.JButton jButtonsave2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
